config/routes.rb
Rails.application.routes.draw do
  resources :dummies

end

app/models/dummy.rb
class Dummy < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dummies_controller.rb
class DummiesController < ApplicationController
  before_action :set_dummy, only: [:show, :edit, :update, :destroy]

  # GET /dummies
  # GET /dummies.json
  def index
    @dummies = Dummy.all
  end

  # GET /dummies/1
  # GET /dummies/1.json
  def show
  end

  # GET /dummies/new
  def new
    @dummy = Dummy.new
  end

  # GET /dummies/1/edit
  def edit
  end

  # POST /dummies
  # POST /dummies.json
  def create
    @dummy = Dummy.new(dummy_params)

    respond_to do |format|
      if @dummy.save
        format.html { redirect_to @dummy, notice: 'Dummy was successfully created.' }
        format.json { render :show, status: :created, location: @dummy }
      else
        format.html { render :new }
        format.json { render json: @dummy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dummies/1
  # PATCH/PUT /dummies/1.json
  def update
    respond_to do |format|
      if @dummy.update(dummy_params)
        format.html { redirect_to @dummy, notice: 'Dummy was successfully updated.' }
        format.json { render :show, status: :ok, location: @dummy }
      else
        format.html { render :edit }
        format.json { render json: @dummy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dummies/1
  # DELETE /dummies/1.json
  def destroy
    @dummy.destroy
    respond_to do |format|
      format.html { redirect_to dummies_url, notice: 'Dummy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dummy
      @dummy = Dummy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dummy_params
      params.require(:dummy).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dummies_helper.rb
module DummiesHelper
end

app/views/dummies/_form.html.erb
<%= form_for(@dummy) do |f| %>
  <% if @dummy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dummy.errors.count, "error") %> prohibited this dummy from being saved:</h2>

      <ul>
      <% @dummy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dummies/edit.html.erb
<h1>Editing Dummy</h1>

<%= render 'form' %>

<%= link_to 'Show', @dummy %> |
<%= link_to 'Back', dummies_path %>

app/views/dummies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dummies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dummies.each do |dummy| %>
      <tr>
        <td><%= dummy.name %></td>
        <td><%= link_to 'Show', dummy %></td>
        <td><%= link_to 'Edit', edit_dummy_path(dummy) %></td>
        <td><%= link_to 'Destroy', dummy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dummy', new_dummy_path %>

app/views/dummies/new.html.erb
<h1>New Dummy</h1>

<%= render 'form' %>

<%= link_to 'Back', dummies_path %>

app/views/dummies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dummy.name %>
</p>

<%= link_to 'Edit', edit_dummy_path(@dummy) %> |
<%= link_to 'Back', dummies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>